apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-iptables
  name: nginx-iptables
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-iptables
  template:
    metadata:
      labels:
        run: nginx-iptables
    spec:
      containers:
      - image: joergm/nginx-iptables
        name: nginx
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
          runAsUser: 0
---
apiVersion: v1 
kind: Service                           
metadata:
  labels:
    run: nginx-iptables
  name: nginx-iptables
spec:
  type: NodePort                        
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-iptables
